#! /bin/bash

WORKDIR=$PWD/tmp

docker kill kamon-grafana-dashboard
docker rm kamon-grafana-dashboard

docker run -d \
	--name kamon-grafana-dashboard \
	-p 80:80 \
	-p 8125:8125/udp \
	-p 8126:8126 \
	-v $WORKDIR/graphite/elasticsearch:/var/lib/elasticsearch \
	-v $WORKDIR/graphite/storage/whisper:/opt/graphite/storage/whisper \
	-v $WORKDIR/graphite/log/storage:/opt/graphite/storage/log \
	-v $WORKDIR/graphite/log/supervisor:/var/log/supervisor \
	cooniur/grafana_graphite
